spring.application.name=project-attorney-users

#spring.datasource.url=${URL_BASE}
#spring.datasource.username=${USER_NAME}
#spring.datasource.password=${PASSWORD}

spring.datasource.url=jdbc:postgresql://ep-crimson-dust-a59y9jhj-pooler.us-east-2.aws.neon.tech/teste?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hGFd9HQl2ZjP

spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=comovcfaraologin2018@gmail.com
spring.mail.password=umldkgikfjre kbof 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000